CREATE TABLE users(
	id INTEGER IDENTITY PRIMARY KEY,
	name VARCHAR(30) NOT NULL,
	email VARCHAR(50) NOT NULL,
	birthDate VARCHAR(15) NOT NULL,
	country VARCHAR(50) NOT NULL,
	password VARCHAR(30) NOT NULL
);